#!/bin/bash
##############################################################################

dns cav01_bse > /dev/null
mv cav01_bse.fld cav01.bse

../../dog -k 13 -m 40 -n 2 -t 1e-7 cav01 > /dev/null


