# Make a PDF of the dog user guide.
#
# $Id$
###############################################################################

# Make a PDF user guide document (guidedog.pdf).
# It is assumed that you have a working latex distribution.

default:
	pdflatex guidedog
	bibtex   guidedog
	pdflatex guidedog
	pdflatex guidedog
